### ISSUE TITLE
!bug - !fparse

### ISSUE THREAD

**Issue by fisherthewol** [fisherthewol/Dave-BOT#8]
Added ```https://www.reddit.com/r/pubattlegrounds/.rss``` successfully to feeds.txt, as a test url.  
When calling !fparse, which should read out newest item from each url in feeds.txt, error is tracebacked from discord.py:  
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "./dave.py", line 134, in fparse
    cfeed = lines[item]
TypeError: list indices must be integers or slices, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 630, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: list indices must be integers or slices, not str
```  
Should be an issue in feedparser if anything, so what am I doing wrong?

**Comment by fisherthewol** [comment]
@EyelessJonny Yo. Look please.

**Comment by fisherthewol** [comment]
created /fparse-bug so I can remove function and push new features to stable. All testing related to this issue should be done on that branch.

**Comment by fisherthewol** [comment]
Closing this - Working on fparse in main branch anyway, functionality could possibly be done through that.
